[tool.poetry]
name = "dust-access-simulator"
version = "0.0.1"
description = "A Simulator for the ECG game Dust Access"
authors = ["Maria Vicidomini <a.vicidomini36@studenti.unisa.it>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
poetry-core = "^2.2.1"
pandas = "^2.3.3"
flet = "^0.28.3"
websockets = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
