services:
  # SERVER
  - type: web
    name: dust-server
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt

    startCommand: python server/server.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: PORT
        sync: false
      - key: PYTHONPATH
        value: "."

    autoDeploy: true

  # CLIENT WEB
  - type: web
    name: dust-client
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        sync: false
      - key: RENDER
        value: "true"
      - key: SERVER_HOST
        fromService:
          type: web
          name: dust-server
          property: host
      - key: SERVER_PORT
        value: "443"