services:
  - type: web
    name: dust-server
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install poetry && poetry install
    startCommand: poetry run python ./server/server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: PORT
        sync: false
    autoDeploy: true

  # 2. Client
  - type: web
    name: dust-client
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install poetry && poetry install
    startCommand: poetry run python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: PORT
        sync: false
      - key: RENDER
        value: "true"
      # Auto-discovery del server
      - key: SERVER_HOST
        fromService:
          type: web
          name: dust-server
          property: host
      - key: SERVER_PORT
        value: "443"